export { ApiClient, createApiClient } from './client';
export type { ApiRequestOptions, CreateClientOptions } from './client';
export { ENVELOPE_RESULT, isApiEnvelope, isSuccessResult, isPendingResult, parseEnvelope } from './envelope';
export type { ApiEnvelope, EnvelopeResultValue } from './envelope';
export {
  ApiError,
  EnvelopeInvalidError,
  HttpStatusError,
  NetworkError,
  ResultFailureError,
  ResultPendingError,
  UnauthorizedError,
} from './errors';
export type { ErrorCode } from './errors';
export { EncryptedLocalStorageTokenStore, InMemoryTokenStore, createDefaultTokenStore } from './token-store';
export type { TokenRecord, TokenScope, TokenStore } from './token-store';
export { fetchUserConfiguration } from './endpoints/configuration';
export type { ConfigurationPayload } from './endpoints/configuration';
export {
  base64ToBytes,
  decryptText,
  encryptText,
  isCryptoAvailable,
  tryDecrypt,
} from './crypto';
export {
  buildWebDevicePayload,
  fetchCmsPage,
  fetchCountries,
  fetchUserDetails,
  forgotPassword,
  getOrCreateDeviceId,
  guestLogin,
  isTokenEnvelope,
  loginWithOtp,
  loginWithPassword,
  logoutUser,
  parseUserProfile,
  sendOtp,
  socialSignIn,
  socialSignup,
  signup,
} from './endpoints/auth';
export type {
  CmsPage,
  CountryPayload,
  DevicePayload,
  FetchCmsPageParams,
  ForgotPasswordParams,
  GuestLoginParams,
  LoginWithOtpParams,
  LoginWithPasswordParams,
  OtpChannel,
  OtpSendResult,
  OtpType,
  SendOtpParams,
  SignupParams,
  SocialProvider,
  SocialSignInParams,
  SocialSignupParams,
  TokenPayload,
  UserProfile,
} from './endpoints/auth';
export {
  fetchMainScreen,
  isHomeEnv,
  parseMainScreen,
} from './endpoints/home';
export type {
  AddMoneyItem,
  BannerCellItem,
  BusinessSegmentItem,
  FetchMainScreenParams,
  MainScreenCell,
  MainScreenCellItem,
  MainScreenResult,
  RecommendedServiceItem,
  ServiceCellItem,
} from './endpoints/home';
export {
  DRAWER_HEADER,
  DRAWER_ITEMS_TILE,
  fetchNavigationDrawer,
  fetchNavigationDrawerConfig,
} from './endpoints/navigation';
export type {
  DrawerEntry,
  DrawerHeaderDefinition,
  DrawerItemDefinition,
  DrawerMenuOptions,
  FetchNavigationDrawerParams,
  LogoutButtonDefinition,
  NavigationDrawer,
  NavigationDrawerConfig,
} from './endpoints/navigation';
export { parsePlaceSearch, searchPlaces } from './endpoints/places';
export type { PlaceOption, PlaceSearchResult, SearchPlacesParams } from './endpoints/places';
export { fetchAreas, parseAreas } from './endpoints/locations';
export type { AreaOption } from './endpoints/locations';
export { fetchNotifications, parseNotifications } from './endpoints/notifications';
export type { NotificationItem } from './endpoints/notifications';
export {
  applyPromo,
  confirmBooking,
  fetchCheckout,
  fetchCheckoutAdditionalInfo,
  fetchCheckoutPayment,
  fetchCars,
  fetchDrivers,
  fetchOutstationDetails,
  fetchPaymentOptions,
  fetchPendingBookingApprovals,
  fetchRentalCars,
  fetchTransferDetails,
  fetchPoolDetails,
  fetchCheckSeats,
  fetchDeliveryPackages,
  fetchDeliveryProductList,
  fetchDeliveryCategoryTypes,
  fetchDeliveryVehiclePackage,
  fetchDeliveryCheckout,
  fetchDeliveryCheckoutDetails,
  confirmDeliveryBooking,
  parseCars,
  parseConfirm,
  parsePendingBookings,
  parseRentalVehicles,
  removePromo,
} from './endpoints/ride';
export type {
  AdditionalInfoParams,
  AdditionalInfoResult,
  CarsResult,
  CategoryOption,
  CheckoutReceiptItem,
  CheckoutResult,
  ConfirmBookingParams,
  ConfirmResult,
  DropPoint,
  FetchCarsParams,
  FetchCheckoutParams,
  FetchCheckoutPaymentParams,
  FetchDriversParams,
  FetchPaymentOptionsParams,
  NearbyDriver,
  OutstationResult,
  OutstationVehicle,
  PaymentMethodOption,
  PendingBooking,
  RentalPackage,
  RentalVehicle,
  ServiceTypeOption,
  TransferPackage,
  TransferVehicle,
  PoolVehicle,
  CheckSeatsResult,
  VehicleOption,
  DeliveryPackage,
  DeliveryProduct,
  DeliveryCategoryType,
  DeliveryVehicle,
  DeliveryDrop,
  DeliveryCheckoutResult,
} from './endpoints/ride';
export {
  addTip,
  autoCancelBooking,
  cancelBooking,
  changeDropAddress,
  fetchBookingDetails,
  fetchCancelReasons,
  fetchReceipt,
  fetchTracking,
  increaseRideRadius,
  parseBookingDetails,
  parseCancelReasons,
  parseReceipt,
  parseTracking,
  rateDriver,
  requestSos,
} from './endpoints/ride-tracking';
export type {
  BookingDetails,
  BookingDriver,
  BookingSos,
  CancelBookingParams,
  CancelReasonItem,
  CancelReasonsResult,
  ChangeDropParams,
  LocationUpdates,
  MovableMarker,
  PolyData,
  RateDriverParams,
  ReceiptLineItem,
  ReceiptResult,
  SosRequestParams,
  SosRequestResult,
  TrackingUpdate,
} from './endpoints/ride-tracking';
export {
  addToFoodCart,
  applyFoodPromo,
  cancelFoodOrder,
  clearFoodCart,
  favouriteBusinessSegment,
  fetchFoodCart,
  fetchFoodChatHistory,
  fetchFoodOrderDetail,
  fetchFoodOrders,
  fetchFoodProductDetails,
  fetchFoodCheckout,
  fetchFoodStoreDetails,
  fetchFoodStores,
  placeFoodOrder,
  rateFoodOrder,
  removeFromFoodCart,
  reorderFood,
  sendFoodChatMessage,
  trackFoodOrder,
  updateFoodCart,
} from './endpoints/food';
export type {
  FoodCart,
  FoodCartItem,
  FoodCategory,
  FoodChatHistory,
  FoodChatMessage,
  FoodCheckoutParams,
  FoodCheckoutResult,
  FoodOrder,
  FoodProduct,
  FoodPromoResult,
  FoodServiceOption,
  FoodStore,
  FoodStoreDetails,
  PlaceOrderParams,
} from './endpoints/food';
export {
  addToStoreCart,
  applyStorePromo,
  cancelStoreOrder,
  clearStoreCart,
  favouriteStoreSegment,
  fetchStoreCart,
  fetchStoreChatHistory,
  fetchStoreOrderDetail,
  fetchStoreOrders,
  fetchStoreCheckout,
  fetchStoreDetails,
  fetchStores,
  placeStoreOrder,
  rateStoreOrder,
  removeFromStoreCart,
  reorderStore,
  searchStoreProducts,
  sendStoreChatMessage,
  trackStoreOrder,
  updateStoreCart,
} from './endpoints/store';
export type {
  Store,
  StoreCart,
  StoreCartItem,
  StoreCategory,
  StoreChatHistory,
  StoreChatMessage,
  StoreCheckoutParams,
  StoreCheckoutResult,
  StoreDetails,
  StoreOrder,
  StorePlaceOrderParams,
  StoreProduct,
  StorePromoResult,
  StoreSearchResult,
  StoreServiceOption,
  StoreTimeSlot,
  StoreSlug,
} from './endpoints/store';
export {
  acceptHandymanBid,
  applyHandymanPromoWeb,
  cancelDeleteHandymanBidOrder,
  cancelHandymanOrder,
  confirmHandymanOrderWeb,
  counterBidHandymanOrder,
  createHandymanBidOrder,
  deleteHandymanCart,
  fetchHandymanBidOrderDetail,
  fetchHandymanBidOrders,
  fetchHandymanCart,
  fetchHandymanCategories,
  fetchHandymanOrderDetail,
  fetchHandymanOrders,
  fetchHandymanProviderDetail,
  fetchHandymanProviders,
  fetchHandymanServices,
  fetchHandymanTimeSlots,
  payHandymanBooking,
  rateHandymanProvider,
  saveHandymanCart,
} from './endpoints/handyman';
export type {
  HandymanAcceptBidResult,
  HandymanAdditionalCharge,
  HandymanBid,
  HandymanBidOrder,
  HandymanCancelReason,
  HandymanCart,
  HandymanCartService,
  HandymanCategory,
  HandymanConfirmParams,
  HandymanCreateBidOrderParams,
  HandymanDeleteCartParams,
  HandymanOrder,
  HandymanOrderDetail,
  HandymanOrderQuery,
  HandymanOrderService,
  HandymanPayResult,
  HandymanPromoResult,
  HandymanProvider,
  HandymanProviderService,
  HandymanSaveCartParams,
  HandymanService,
  HandymanServicesResponse,
  HandymanTimeSlot,
  HandymanTimeSlotResponse,
} from './endpoints/handyman';
export {
  applyLaundryPromo,
  cancelLaundryOrder,
  confirmLaundryOrder,
  deleteLaundryCart,
  fetchLaundryCart,
  fetchLaundryCategories,
  fetchLaundryOrderDetail,
  fetchLaundryOrders,
  fetchLaundryOutletDetail,
  fetchLaundryOutlets,
  fetchLaundryServices,
  fetchLaundryTimeSlots,
  rateLaundryOutlet,
  saveLaundryCart,
  verifyLaundryOtp,
} from './endpoints/laundry';
export type {
  LaundryCancelReason,
  LaundryCart,
  LaundryCartItem,
  LaundryCategory,
  LaundryConfirmParams,
  LaundryConfirmResult,
  LaundryDeleteCartParams,
  LaundryOrder,
  LaundryOrderDetail,
  LaundryOrderItem,
  LaundryOrderQuery,
  LaundryOtpResult,
  LaundryOutlet,
  LaundryPaymentDetail,
  LaundrySaveCartItem,
  LaundrySaveCartParams,
  LaundryService,
  LaundryStatusStep,
  LaundryTimeSlot,
  LaundryTimeSlotResponse,
} from './endpoints/laundry';
export {
  cancelBusBooking,
  confirmBusBooking,
  fetchAvailableBuses,
  fetchBusBookingDetail,
  fetchBusBookings,
  fetchBusCheckout,
  fetchRouteStops,
  fetchSeatMap,
  searchBusRoutes,
} from './endpoints/bus';
export type {
  BusAvailableBus,
  BusBooking,
  BusBookingConfirmResult,
  BusBookingDetail,
  BusCheckoutParams,
  BusCheckoutResult,
  BusRouteStop,
  BusSeatDetail,
  BusSeatMap,
  FetchAvailableBusesParams,
  FetchRouteStopsParams,
  FetchSeatMapParams,
  SearchBusRoutesParams,
} from './endpoints/bus';
export {
  bookCarpoolingRide,
  cancelCarpoolingRide,
  cancelOfferRide,
  fetchCarpoolingRideDetail,
  fetchOfferedRides,
  fetchTakenRides,
  offerCarpoolingRide,
  searchCarpoolingRides,
  CARPOOLING_STATUS_LABELS,
} from './endpoints/carpool';
export type {
  BookRideParams,
  CarpoolingBooking,
  CarpoolingRide,
  CarpoolingRideDetail,
  CarpoolingRideStatus,
  CarpoolingRoutePoint,
  CarpoolingVehicle,
  OfferRideParams,
  SearchCarpoolingRidesParams,
} from './endpoints/carpool';
export {
  changePassword,
  deleteAccount,
  fetchAccountDocuments,
  fetchAccountProfile,
  saveAccountDocument,
  updateAccountProfile,
} from './endpoints/account';
export type {
  AccountDocument,
  AccountProfile,
} from './endpoints/account';
export {
  addMoneyToWallet,
  checkTransferUser,
  fetchCashoutHistory,
  fetchCashoutMethods,
  fetchWalletTransactions,
  requestCashout,
  transferWalletMoney,
} from './endpoints/wallet';
export type {
  CashoutHistoryItem,
  CashoutRequest,
  CheckUserResult,
  WalletResult,
  WalletTransaction,
} from './endpoints/wallet';
export {
  fetchActiveBookings,
  fetchBookingDetail,
  fetchBookingHistory,
} from './endpoints/history';
export type {
  HistoryBooking,
  HistoryDetail,
  HistoryPageResult,
} from './endpoints/history';
export {
  createSosContact,
  deleteSosContact,
  fetchSosContacts,
  sendSosRequest,
} from './endpoints/sos';
export type { SosContact } from './endpoints/sos';
export {
  addFavouriteLocation,
  deleteFavouriteLocation,
  fetchFavouriteDrivers,
  fetchFavouriteLocations,
  toggleFavouriteDriver,
} from './endpoints/favourites';
export type {
  FavouriteDriver,
  FavouriteLocation,
} from './endpoints/favourites';
export {
  addFamilyMember,
  deleteFamilyMember,
  fetchFamilyMembers,
} from './endpoints/family';
export type { FamilyMember } from './endpoints/family';
export { fetchReferral } from './endpoints/referral';
export type { ReferralInfo } from './endpoints/referral';
export {
  fetchRedeemedGifts,
  fetchRewardGiftList,
  fetchRewardHistory,
  fetchRewardPoints,
  redeemRewardGift,
  redeemRewardPoints,
} from './endpoints/rewards';
export type {
  RewardGift,
  RewardHistoryItem,
  RewardSummary,
} from './endpoints/rewards';
export {
  activateSubscription,
  fetchActiveSubscription,
  fetchSubscriptionHistory,
  fetchSubscriptionPackages,
} from './endpoints/subscriptions';
export type { SubscriptionPackage } from './endpoints/subscriptions';
export { fetchChatHistory, sendChatMessage } from './endpoints/chat';
export type { ChatMessage } from './endpoints/chat';
export {
  fetchSupportChannels,
  fetchSupportThreads,
  sendSupportMessage,
} from './endpoints/support';
export type {
  SupportChannel,
  SupportThread,
} from './endpoints/support';
export { deleteSavedCard, fetchSavedCards } from './endpoints/cards';
export type { SavedCard } from './endpoints/cards';
export { fetchPriceCard } from './endpoints/pricecard';
export type {
  PriceCardService,
  PriceCardVehicle,
} from './endpoints/pricecard';
export {
  acceptRejectDriverHandymanOrder,
  activateDriverSubscriptionPackage,
  addDriverDocument,
  addDriverVehicle,
  addDriverWalletMoney,
  arriveDriverHandymanOrder,
  bidDriverHandymanOrder,
  buildDriverDevicePayload,
  cancelDriverHandymanOrder,
  changeDriverVehicle,
  completeDriverHandymanOrder,
  deleteDriverGalleryImage,
  deliverLaundryDriverOrder,
  driverArrivedAtPickup,
  driverBookingAcceptReject,
  driverBookingOrderPicked,
  driverCompleteBookingOrder,
  driverConfirmPayment,
  driverDemoOnboard,
  driverEndBooking,
  driverLoginWithOtp,
  driverLoginWithPassword,
  endBusDriverBooking,
  endDriverHandymanOrder,
  fetchBusBookingStopDetail,
  fetchBusDriverBooking,
  fetchBusDriverBookings,
  fetchBusDriverHome,
  fetchBusMasterBookings,
  fetchBusPassengerBooking,
  fetchDriverAccountEarnings,
  fetchDriverActiveBookings,
  fetchDriverActiveSubscription,
  fetchDriverAllDocuments,
  fetchDriverBookingDetails,
  fetchDriverBookingOrderInfo,
  fetchDriverCashoutHistory,
  fetchDriverChatHistory,
  fetchDriverConfiguration,
  fetchDriverDetails,
  fetchDriverDirection,
  fetchDriverDocuments,
  fetchDriverEnrolledSegments,
  fetchDriverExpiredDocuments,
  fetchDriverGallery,
  fetchDriverHandymanOrder,
  fetchDriverHandymanOrders,
  fetchDriverMainScreenConfig,
  fetchDriverOnlineConfig,
  fetchDriverPastBookings,
  fetchDriverPaymentInfo,
  fetchDriverSegments,
  fetchDriverSubscriptionHistory,
  fetchDriverSubscriptionPackages,
  fetchDriverVehicles,
  fetchDriverWalletTransactions,
  fetchServiceTimeSlots,
  fetchSegmentServicesConfig,
  fetchVehicleConfiguration,
  fetchVehicleModels,
  getOrCreateDriverDeviceId,
  getOrCreatePlayerId,
  logoutDriver,
  parseDriverAccountEarnings,
  parseDriverBooking,
  parseDriverDocuments,
  parseDriverMainScreenConfig,
  parseDriverOnlineConfig,
  parseDriverSegment,
  parseDriverSegmentList,
  parseDriverSegmentServicesConfig,
  parseDriverSubscriptionPackage,
  parseDriverTimeSlots,
  parseDriverVehicle,
  parseDriverWalletTransaction,
  pickupDropBusDriverBooking,
  raiseDriverHandymanConcern,
  requestDriverCashout,
  requestDriverHandymanStartOtp,
  requestDriverVehicleByCode,
  saveDriverGalleryImage,
  saveDriverOnlineConfig,
  saveDriverSegmentConfig,
  saveDriverServiceTimeSlot,
  saveDriverTimeSlots,
  sendDriverChatMessage,
  sendDriverInDriveCounter,
  sendDriverOtp,
  setDriverOnlineState,
  startBusDriverBooking,
  startDriverHandymanOrder,
  submitDriverRegStepFive,
  submitDriverRegStepOne,
  submitDriverRegStepThree,
  submitDriverRegStepTwo,
  updateBusStopStatus,
  updateDriverHandymanPaymentStatus,
  updateDriverLocation,
  verifyDriverVehicleOtp,
  verifyLaundryDriverDeliveryOtp,
  withdrawDriverWallet,
} from './endpoints/driver';
export type {
  ActivateDriverSubscriptionParams,
  AddDriverDocumentParams,
  AddDriverVehicleParams,
  AddDriverVehicleResult,
  AddDriverWalletMoneyParams,
  BusDriverBookingParams,
  DeleteDriverGalleryImageParams,
  DriverAccountEarnings,
  DriverAcceptReject,
  DriverAcceptRejectParams,
  DriverBooking,
  DriverBookingStatus,
  DriverCashoutHistoryItem,
  DriverChatMessage,
  DriverConfirmPaymentParams,
  DriverConfigurationPayload,
  DriverDevicePayload,
  DriverDirectionParams,
  DriverDirectionResult,
  DriverDocumentFor,
  DriverDocumentItem,
  DriverDocumentsResult,
  DriverEarningsDay,
  DriverEarningsTrip,
  DriverGalleryImage,
  DriverHandymanOrderParams,
  DriverInDriveCounterParams,
  DriverLoginWithOtpParams,
  DriverLoginWithPasswordParams,
  DriverMainScreenConfig,
  DriverOnlineConfig,
  DriverOtpSendResult,
  DriverPaymentInfo,
  DriverProfile,
  DriverSaveOnlineConfigParams,
  DriverSegmentDocumentGroup,
  DriverSegmentListItem,
  DriverSegmentListResult,
  DriverSegmentServiceOption,
  DriverSegmentServicesConfig,
  DriverSendOtpParams,
  DriverStepHolder,
  DriverStepType,
  DriverSubscriptionPackageItem,
  DriverSubscriptionPackDetails,
  DriverSubscriptionPackagesResult,
  DriverSubscriptionPaymentMethod,
  DriverTimeSlot,
  DriverTimeSlotDay,
  DriverTimeSlotResult,
  DriverTokenPayload,
  DriverVehicleBrief,
  DriverVehicleConfigurationResult,
  DriverVehicleDocumentGroup,
  DriverVehicleKindOption,
  DriverVehicleListItem,
  DriverVehicleModelOption,
  DriverVehicleVerificationStatus,
  DriverWalletDetailLine,
  DriverWalletDuration,
  DriverWalletFilter,
  DriverWalletResult,
  DriverWalletTransactionItem,
  DriverWizardStepParams,
  DriverWizardStepResult,
  DriverWizardStepSubmitter,
  FetchDriverAccountEarningsParams,
  FetchDriverActiveSubscriptionParams,
  FetchDriverChatParams,
  FetchDriverDocumentsParams,
  FetchDriverGalleryParams,
  FetchDriverSegmentsParams,
  FetchDriverSubscriptionHistoryParams,
  FetchDriverSubscriptionPackagesParams,
  FetchSegmentServicesConfigParams,
  FetchServiceTimeSlotsParams,
  FetchVehicleModelsParams,
  LaundryDriverDeliveryParams,
  RequestDriverCashoutParams,
  RequestDriverVehicleByCodeParams,
  SaveDriverGalleryImageParams,
  SaveDriverTimeSlotsParams,
  SendDriverChatMessageParams,
  VerifyDriverVehicleOtpParams,
} from './endpoints/driver';
export { fetchPromotions } from './endpoints/promotions';
export type { PromotionItem } from './endpoints/promotions';