// Generated from Google libphonenumber metadata (mobile length preferred, general fallback).
// phonecode is stored WITHOUT a leading '+' — UI adds '+' when displaying.
// Names/codes follow the product's country list (247 entries incl. territories).
import type { CountryOption } from './index';

export function normalizePhoneCode(value: string | number): string {
  return String(value)
    .trim()
    .replace(/^\+/, '')
    .replace(/\s+/g, '-');
}

// The dial prefix used in E.164 numbers is everything before a territory
// suffix (e.g. '1-684' dials as +1, '44-1624' dials as +44).
export function callingCodeOf(phonecode: string): string {
  return normalizePhoneCode(phonecode).split('-')[0] ?? '';
}

export function phoneToE164(countryPhoneCode: string | undefined, nationalDigits: string): string {
  const cc = callingCodeOf(countryPhoneCode ?? '');
  return `+${cc}${nationalDigits}`;
}

export function isNationalNumberValid(
  country: Pick<CountryOption, 'minNumPhone' | 'maxNumPhone'> | null | undefined,
  nationalDigits: string,
): boolean {
  const digits = nationalDigits.replace(/\D/g, '');
  const min = country?.minNumPhone ? Number(country.minNumPhone) : 0;
  const max = country?.maxNumPhone ? Number(country.maxNumPhone) : 15;
  if (min <= 0 || max <= 0) {
    return digits.length >= 8;
  }
  return digits.length >= min && digits.length <= max;
}

export const ALL_COUNTRIES: CountryOption[] = [
  { id: 1, phonecode: '93', country_code: 'AF', isoCode: 'AF', name: 'Afghanistan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 2, phonecode: '355', country_code: 'AL', isoCode: 'AL', name: 'Albania', minNumPhone: '9', maxNumPhone: '9' },
  { id: 3, phonecode: '213', country_code: 'DZ', isoCode: 'DZ', name: 'Algeria', minNumPhone: '9', maxNumPhone: '9' },
  { id: 4, phonecode: '1-684', country_code: 'AS', isoCode: 'AS', name: 'American Samoa', minNumPhone: '10', maxNumPhone: '10' },
  { id: 5, phonecode: '376', country_code: 'AD', isoCode: 'AD', name: 'Andorra', minNumPhone: '6', maxNumPhone: '9' },
  { id: 6, phonecode: '244', country_code: 'AO', isoCode: 'AO', name: 'Angola', minNumPhone: '9', maxNumPhone: '9' },
  { id: 7, phonecode: '1-264', country_code: 'AI', isoCode: 'AI', name: 'Anguilla', minNumPhone: '10', maxNumPhone: '10' },
  { id: 8, phonecode: '1-268', country_code: 'AG', isoCode: 'AG', name: 'Antigua and Barbuda', minNumPhone: '10', maxNumPhone: '10' },
  { id: 9, phonecode: '54', country_code: 'AR', isoCode: 'AR', name: 'Argentina', minNumPhone: '10', maxNumPhone: '11' },
  { id: 10, phonecode: '374', country_code: 'AM', isoCode: 'AM', name: 'Armenia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 11, phonecode: '297', country_code: 'AW', isoCode: 'AW', name: 'Aruba', minNumPhone: '7', maxNumPhone: '7' },
  { id: 12, phonecode: '61', country_code: 'AU', isoCode: 'AU', name: 'Australia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 13, phonecode: '43', country_code: 'AT', isoCode: 'AT', name: 'Austria', minNumPhone: '7', maxNumPhone: '13' },
  { id: 14, phonecode: '994', country_code: 'AZ', isoCode: 'AZ', name: 'Azerbaijan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 15, phonecode: '1-242', country_code: 'BS', isoCode: 'BS', name: 'Bahamas', minNumPhone: '10', maxNumPhone: '10' },
  { id: 16, phonecode: '973', country_code: 'BH', isoCode: 'BH', name: 'Bahrain', minNumPhone: '8', maxNumPhone: '8' },
  { id: 17, phonecode: '880', country_code: 'BD', isoCode: 'BD', name: 'Bangladesh', minNumPhone: '10', maxNumPhone: '10' },
  { id: 18, phonecode: '1-246', country_code: 'BB', isoCode: 'BB', name: 'Barbados', minNumPhone: '10', maxNumPhone: '10' },
  { id: 19, phonecode: '375', country_code: 'BY', isoCode: 'BY', name: 'Belarus', minNumPhone: '9', maxNumPhone: '9' },
  { id: 20, phonecode: '32', country_code: 'BE', isoCode: 'BE', name: 'Belgium', minNumPhone: '9', maxNumPhone: '9' },
  { id: 21, phonecode: '501', country_code: 'BZ', isoCode: 'BZ', name: 'Belize', minNumPhone: '7', maxNumPhone: '7' },
  { id: 22, phonecode: '229', country_code: 'BJ', isoCode: 'BJ', name: 'Benin', minNumPhone: '8', maxNumPhone: '10' },
  { id: 23, phonecode: '1-441', country_code: 'BM', isoCode: 'BM', name: 'Bermuda', minNumPhone: '10', maxNumPhone: '10' },
  { id: 24, phonecode: '975', country_code: 'BT', isoCode: 'BT', name: 'Bhutan', minNumPhone: '8', maxNumPhone: '8' },
  { id: 25, phonecode: '591', country_code: 'BO', isoCode: 'BO', name: 'Bolivia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 26, phonecode: '387', country_code: 'BA', isoCode: 'BA', name: 'Bosnia and Herzegovina', minNumPhone: '8', maxNumPhone: '9' },
  { id: 27, phonecode: '267', country_code: 'BW', isoCode: 'BW', name: 'Botswana', minNumPhone: '8', maxNumPhone: '8' },
  { id: 28, phonecode: '55', country_code: 'BR', isoCode: 'BR', name: 'Brazil', minNumPhone: '10', maxNumPhone: '11' },
  { id: 29, phonecode: '246', country_code: 'IO', isoCode: 'IO', name: 'British Indian Ocean Territory', minNumPhone: '7', maxNumPhone: '7' },
  { id: 30, phonecode: '1-284', country_code: 'VG', isoCode: 'VG', name: 'British Virgin Islands', minNumPhone: '10', maxNumPhone: '10' },
  { id: 31, phonecode: '673', country_code: 'BN', isoCode: 'BN', name: 'Brunei', minNumPhone: '7', maxNumPhone: '7' },
  { id: 32, phonecode: '359', country_code: 'BG', isoCode: 'BG', name: 'Bulgaria', minNumPhone: '8', maxNumPhone: '9' },
  { id: 33, phonecode: '226', country_code: 'BF', isoCode: 'BF', name: 'Burkina Faso', minNumPhone: '8', maxNumPhone: '8' },
  { id: 34, phonecode: '257', country_code: 'BI', isoCode: 'BI', name: 'Burundi', minNumPhone: '8', maxNumPhone: '8' },
  { id: 35, phonecode: '855', country_code: 'KH', isoCode: 'KH', name: 'Cambodia', minNumPhone: '8', maxNumPhone: '9' },
  { id: 36, phonecode: '237', country_code: 'CM', isoCode: 'CM', name: 'Cameroon', minNumPhone: '9', maxNumPhone: '9' },
  { id: 37, phonecode: '1', country_code: 'CA', isoCode: 'CA', name: 'Canada', minNumPhone: '10', maxNumPhone: '10' },
  { id: 38, phonecode: '238', country_code: 'CV', isoCode: 'CV', name: 'Cape Verde', minNumPhone: '7', maxNumPhone: '7' },
  { id: 39, phonecode: '1-345', country_code: 'KY', isoCode: 'KY', name: 'Cayman Islands', minNumPhone: '10', maxNumPhone: '10' },
  { id: 40, phonecode: '236', country_code: 'CF', isoCode: 'CF', name: 'Central African Republic', minNumPhone: '8', maxNumPhone: '8' },
  { id: 41, phonecode: '235', country_code: 'TD', isoCode: 'TD', name: 'Chad', minNumPhone: '8', maxNumPhone: '8' },
  { id: 42, phonecode: '56', country_code: 'CL', isoCode: 'CL', name: 'Chile', minNumPhone: '9', maxNumPhone: '9' },
  { id: 43, phonecode: '86', country_code: 'CN', isoCode: 'CN', name: 'China', minNumPhone: '11', maxNumPhone: '11' },
  { id: 44, phonecode: '61-89164', country_code: 'CX', isoCode: 'CX', name: 'Christmas Island', minNumPhone: '9', maxNumPhone: '9' },
  { id: 45, phonecode: '61-89162', country_code: 'CC', isoCode: 'CC', name: 'Cocos (Keeling) Islands', minNumPhone: '9', maxNumPhone: '9' },
  { id: 46, phonecode: '57', country_code: 'CO', isoCode: 'CO', name: 'Colombia', minNumPhone: '10', maxNumPhone: '10' },
  { id: 47, phonecode: '269', country_code: 'KM', isoCode: 'KM', name: 'Comoros', minNumPhone: '7', maxNumPhone: '7' },
  { id: 48, phonecode: '243', country_code: 'CD', isoCode: 'CD', name: 'Congo (DRC)', minNumPhone: '7', maxNumPhone: '9' },
  { id: 49, phonecode: '242', country_code: 'CG', isoCode: 'CG', name: 'Congo (Republic)', minNumPhone: '9', maxNumPhone: '9' },
  { id: 50, phonecode: '682', country_code: 'CK', isoCode: 'CK', name: 'Cook Islands', minNumPhone: '5', maxNumPhone: '5' },
  { id: 51, phonecode: '506', country_code: 'CR', isoCode: 'CR', name: 'Costa Rica', minNumPhone: '8', maxNumPhone: '8' },
  { id: 52, phonecode: '385', country_code: 'HR', isoCode: 'HR', name: 'Croatia', minNumPhone: '8', maxNumPhone: '9' },
  { id: 53, phonecode: '53', country_code: 'CU', isoCode: 'CU', name: 'Cuba', minNumPhone: '8', maxNumPhone: '8' },
  { id: 54, phonecode: '599', country_code: 'CW', isoCode: 'CW', name: 'Curacao', minNumPhone: '7', maxNumPhone: '8' },
  { id: 55, phonecode: '357', country_code: 'CY', isoCode: 'CY', name: 'Cyprus', minNumPhone: '8', maxNumPhone: '8' },
  { id: 56, phonecode: '420', country_code: 'CZ', isoCode: 'CZ', name: 'Czechia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 57, phonecode: '45', country_code: 'DK', isoCode: 'DK', name: 'Denmark', minNumPhone: '8', maxNumPhone: '8' },
  { id: 58, phonecode: '253', country_code: 'DJ', isoCode: 'DJ', name: 'Djibouti', minNumPhone: '8', maxNumPhone: '8' },
  { id: 59, phonecode: '1-767', country_code: 'DM', isoCode: 'DM', name: 'Dominica', minNumPhone: '10', maxNumPhone: '10' },
  { id: 60, phonecode: '1-809', country_code: 'DO', isoCode: 'DO', name: 'Dominican Republic', minNumPhone: '10', maxNumPhone: '10' },
  { id: 61, phonecode: '593', country_code: 'EC', isoCode: 'EC', name: 'Ecuador', minNumPhone: '9', maxNumPhone: '9' },
  { id: 62, phonecode: '20', country_code: 'EG', isoCode: 'EG', name: 'Egypt', minNumPhone: '10', maxNumPhone: '10' },
  { id: 63, phonecode: '503', country_code: 'SV', isoCode: 'SV', name: 'El Salvador', minNumPhone: '8', maxNumPhone: '8' },
  { id: 64, phonecode: '240', country_code: 'GQ', isoCode: 'GQ', name: 'Equatorial Guinea', minNumPhone: '9', maxNumPhone: '9' },
  { id: 65, phonecode: '291', country_code: 'ER', isoCode: 'ER', name: 'Eritrea', minNumPhone: '7', maxNumPhone: '7' },
  { id: 66, phonecode: '372', country_code: 'EE', isoCode: 'EE', name: 'Estonia', minNumPhone: '7', maxNumPhone: '8' },
  { id: 67, phonecode: '268', country_code: 'SZ', isoCode: 'SZ', name: 'Eswatini', minNumPhone: '8', maxNumPhone: '8' },
  { id: 68, phonecode: '251', country_code: 'ET', isoCode: 'ET', name: 'Ethiopia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 69, phonecode: '500', country_code: 'FK', isoCode: 'FK', name: 'Falkland Islands', minNumPhone: '5', maxNumPhone: '5' },
  { id: 70, phonecode: '298', country_code: 'FO', isoCode: 'FO', name: 'Faroe Islands', minNumPhone: '6', maxNumPhone: '6' },
  { id: 71, phonecode: '679', country_code: 'FJ', isoCode: 'FJ', name: 'Fiji', minNumPhone: '7', maxNumPhone: '7' },
  { id: 72, phonecode: '358', country_code: 'FI', isoCode: 'FI', name: 'Finland', minNumPhone: '6', maxNumPhone: '10' },
  { id: 73, phonecode: '33', country_code: 'FR', isoCode: 'FR', name: 'France', minNumPhone: '9', maxNumPhone: '9' },
  { id: 74, phonecode: '594', country_code: 'GF', isoCode: 'GF', name: 'French Guiana', minNumPhone: '9', maxNumPhone: '9' },
  { id: 75, phonecode: '689', country_code: 'PF', isoCode: 'PF', name: 'French Polynesia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 76, phonecode: '241', country_code: 'GA', isoCode: 'GA', name: 'Gabon', minNumPhone: '7', maxNumPhone: '8' },
  { id: 77, phonecode: '220', country_code: 'GM', isoCode: 'GM', name: 'Gambia', minNumPhone: '7', maxNumPhone: '7' },
  { id: 78, phonecode: '995', country_code: 'GE', isoCode: 'GE', name: 'Georgia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 79, phonecode: '49', country_code: 'DE', isoCode: 'DE', name: 'Germany', minNumPhone: '10', maxNumPhone: '11' },
  { id: 80, phonecode: '233', country_code: 'GH', isoCode: 'GH', name: 'Ghana', minNumPhone: '9', maxNumPhone: '9' },
  { id: 81, phonecode: '350', country_code: 'GI', isoCode: 'GI', name: 'Gibraltar', minNumPhone: '8', maxNumPhone: '8' },
  { id: 82, phonecode: '30', country_code: 'GR', isoCode: 'GR', name: 'Greece', minNumPhone: '10', maxNumPhone: '10' },
  { id: 83, phonecode: '299', country_code: 'GL', isoCode: 'GL', name: 'Greenland', minNumPhone: '6', maxNumPhone: '6' },
  { id: 84, phonecode: '1-473', country_code: 'GD', isoCode: 'GD', name: 'Grenada', minNumPhone: '10', maxNumPhone: '10' },
  { id: 85, phonecode: '590', country_code: 'GP', isoCode: 'GP', name: 'Guadeloupe', minNumPhone: '9', maxNumPhone: '9' },
  { id: 86, phonecode: '1-671', country_code: 'GU', isoCode: 'GU', name: 'Guam', minNumPhone: '10', maxNumPhone: '10' },
  { id: 87, phonecode: '502', country_code: 'GT', isoCode: 'GT', name: 'Guatemala', minNumPhone: '8', maxNumPhone: '8' },
  { id: 88, phonecode: '44-1481', country_code: 'GG', isoCode: 'GG', name: 'Guernsey', minNumPhone: '10', maxNumPhone: '10' },
  { id: 89, phonecode: '224', country_code: 'GN', isoCode: 'GN', name: 'Guinea', minNumPhone: '9', maxNumPhone: '9' },
  { id: 90, phonecode: '245', country_code: 'GW', isoCode: 'GW', name: 'Guinea-Bissau', minNumPhone: '9', maxNumPhone: '9' },
  { id: 91, phonecode: '592', country_code: 'GY', isoCode: 'GY', name: 'Guyana', minNumPhone: '7', maxNumPhone: '7' },
  { id: 92, phonecode: '509', country_code: 'HT', isoCode: 'HT', name: 'Haiti', minNumPhone: '8', maxNumPhone: '8' },
  { id: 93, phonecode: '504', country_code: 'HN', isoCode: 'HN', name: 'Honduras', minNumPhone: '8', maxNumPhone: '8' },
  { id: 94, phonecode: '852', country_code: 'HK', isoCode: 'HK', name: 'Hong Kong', minNumPhone: '8', maxNumPhone: '8' },
  { id: 95, phonecode: '36', country_code: 'HU', isoCode: 'HU', name: 'Hungary', minNumPhone: '9', maxNumPhone: '9' },
  { id: 96, phonecode: '354', country_code: 'IS', isoCode: 'IS', name: 'Iceland', minNumPhone: '7', maxNumPhone: '9' },
  { id: 97, phonecode: '91', country_code: 'IN', isoCode: 'IN', name: 'India', minNumPhone: '10', maxNumPhone: '10' },
  { id: 98, phonecode: '62', country_code: 'ID', isoCode: 'ID', name: 'Indonesia', minNumPhone: '9', maxNumPhone: '12' },
  { id: 99, phonecode: '98', country_code: 'IR', isoCode: 'IR', name: 'Iran', minNumPhone: '10', maxNumPhone: '10' },
  { id: 100, phonecode: '964', country_code: 'IQ', isoCode: 'IQ', name: 'Iraq', minNumPhone: '10', maxNumPhone: '10' },
  { id: 101, phonecode: '353', country_code: 'IE', isoCode: 'IE', name: 'Ireland', minNumPhone: '9', maxNumPhone: '9' },
  { id: 102, phonecode: '44-1624', country_code: 'IM', isoCode: 'IM', name: 'Isle of Man', minNumPhone: '10', maxNumPhone: '10' },
  { id: 103, phonecode: '972', country_code: 'IL', isoCode: 'IL', name: 'Israel', minNumPhone: '9', maxNumPhone: '9' },
  { id: 104, phonecode: '39', country_code: 'IT', isoCode: 'IT', name: 'Italy', minNumPhone: '9', maxNumPhone: '10' },
  { id: 105, phonecode: '225', country_code: 'CI', isoCode: 'CI', name: 'Ivory Coast', minNumPhone: '10', maxNumPhone: '10' },
  { id: 106, phonecode: '1-876', country_code: 'JM', isoCode: 'JM', name: 'Jamaica', minNumPhone: '10', maxNumPhone: '10' },
  { id: 107, phonecode: '81', country_code: 'JP', isoCode: 'JP', name: 'Japan', minNumPhone: '10', maxNumPhone: '10' },
  { id: 108, phonecode: '44-1534', country_code: 'JE', isoCode: 'JE', name: 'Jersey', minNumPhone: '10', maxNumPhone: '10' },
  { id: 109, phonecode: '962', country_code: 'JO', isoCode: 'JO', name: 'Jordan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 110, phonecode: '7', country_code: 'KZ', isoCode: 'KZ', name: 'Kazakhstan', minNumPhone: '10', maxNumPhone: '10' },
  { id: 111, phonecode: '254', country_code: 'KE', isoCode: 'KE', name: 'Kenya', minNumPhone: '9', maxNumPhone: '9' },
  { id: 112, phonecode: '686', country_code: 'KI', isoCode: 'KI', name: 'Kiribati', minNumPhone: '8', maxNumPhone: '8' },
  { id: 113, phonecode: '383', country_code: 'XK', isoCode: 'XK', name: 'Kosovo', minNumPhone: '8', maxNumPhone: '8' },
  { id: 114, phonecode: '965', country_code: 'KW', isoCode: 'KW', name: 'Kuwait', minNumPhone: '8', maxNumPhone: '8' },
  { id: 115, phonecode: '996', country_code: 'KG', isoCode: 'KG', name: 'Kyrgyzstan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 116, phonecode: '856', country_code: 'LA', isoCode: 'LA', name: 'Laos', minNumPhone: '10', maxNumPhone: '10' },
  { id: 117, phonecode: '371', country_code: 'LV', isoCode: 'LV', name: 'Latvia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 118, phonecode: '961', country_code: 'LB', isoCode: 'LB', name: 'Lebanon', minNumPhone: '7', maxNumPhone: '8' },
  { id: 119, phonecode: '266', country_code: 'LS', isoCode: 'LS', name: 'Lesotho', minNumPhone: '8', maxNumPhone: '8' },
  { id: 120, phonecode: '231', country_code: 'LR', isoCode: 'LR', name: 'Liberia', minNumPhone: '7', maxNumPhone: '9' },
  { id: 121, phonecode: '218', country_code: 'LY', isoCode: 'LY', name: 'Libya', minNumPhone: '9', maxNumPhone: '9' },
  { id: 122, phonecode: '423', country_code: 'LI', isoCode: 'LI', name: 'Liechtenstein', minNumPhone: '7', maxNumPhone: '9' },
  { id: 123, phonecode: '370', country_code: 'LT', isoCode: 'LT', name: 'Lithuania', minNumPhone: '8', maxNumPhone: '8' },
  { id: 124, phonecode: '352', country_code: 'LU', isoCode: 'LU', name: 'Luxembourg', minNumPhone: '9', maxNumPhone: '9' },
  { id: 125, phonecode: '853', country_code: 'MO', isoCode: 'MO', name: 'Macau', minNumPhone: '8', maxNumPhone: '8' },
  { id: 126, phonecode: '261', country_code: 'MG', isoCode: 'MG', name: 'Madagascar', minNumPhone: '9', maxNumPhone: '9' },
  { id: 127, phonecode: '265', country_code: 'MW', isoCode: 'MW', name: 'Malawi', minNumPhone: '9', maxNumPhone: '9' },
  { id: 128, phonecode: '60', country_code: 'MY', isoCode: 'MY', name: 'Malaysia', minNumPhone: '9', maxNumPhone: '10' },
  { id: 129, phonecode: '960', country_code: 'MV', isoCode: 'MV', name: 'Maldives', minNumPhone: '7', maxNumPhone: '7' },
  { id: 130, phonecode: '223', country_code: 'ML', isoCode: 'ML', name: 'Mali', minNumPhone: '8', maxNumPhone: '8' },
  { id: 131, phonecode: '356', country_code: 'MT', isoCode: 'MT', name: 'Malta', minNumPhone: '8', maxNumPhone: '8' },
  { id: 132, phonecode: '692', country_code: 'MH', isoCode: 'MH', name: 'Marshall Islands', minNumPhone: '7', maxNumPhone: '7' },
  { id: 133, phonecode: '596', country_code: 'MQ', isoCode: 'MQ', name: 'Martinique', minNumPhone: '9', maxNumPhone: '9' },
  { id: 134, phonecode: '222', country_code: 'MR', isoCode: 'MR', name: 'Mauritania', minNumPhone: '8', maxNumPhone: '8' },
  { id: 135, phonecode: '230', country_code: 'MU', isoCode: 'MU', name: 'Mauritius', minNumPhone: '8', maxNumPhone: '8' },
  { id: 136, phonecode: '262', country_code: 'YT', isoCode: 'YT', name: 'Mayotte', minNumPhone: '9', maxNumPhone: '9' },
  { id: 137, phonecode: '52', country_code: 'MX', isoCode: 'MX', name: 'Mexico', minNumPhone: '10', maxNumPhone: '10' },
  { id: 138, phonecode: '691', country_code: 'FM', isoCode: 'FM', name: 'Micronesia', minNumPhone: '7', maxNumPhone: '7' },
  { id: 139, phonecode: '373', country_code: 'MD', isoCode: 'MD', name: 'Moldova', minNumPhone: '8', maxNumPhone: '8' },
  { id: 140, phonecode: '377', country_code: 'MC', isoCode: 'MC', name: 'Monaco', minNumPhone: '8', maxNumPhone: '9' },
  { id: 141, phonecode: '976', country_code: 'MN', isoCode: 'MN', name: 'Mongolia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 142, phonecode: '382', country_code: 'ME', isoCode: 'ME', name: 'Montenegro', minNumPhone: '8', maxNumPhone: '8' },
  { id: 143, phonecode: '1-664', country_code: 'MS', isoCode: 'MS', name: 'Montserrat', minNumPhone: '10', maxNumPhone: '10' },
  { id: 144, phonecode: '212', country_code: 'MA', isoCode: 'MA', name: 'Morocco', minNumPhone: '9', maxNumPhone: '9' },
  { id: 145, phonecode: '258', country_code: 'MZ', isoCode: 'MZ', name: 'Mozambique', minNumPhone: '9', maxNumPhone: '9' },
  { id: 146, phonecode: '95', country_code: 'MM', isoCode: 'MM', name: 'Myanmar', minNumPhone: '7', maxNumPhone: '10' },
  { id: 147, phonecode: '264', country_code: 'NA', isoCode: 'NA', name: 'Namibia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 148, phonecode: '674', country_code: 'NR', isoCode: 'NR', name: 'Nauru', minNumPhone: '7', maxNumPhone: '7' },
  { id: 149, phonecode: '977', country_code: 'NP', isoCode: 'NP', name: 'Nepal', minNumPhone: '10', maxNumPhone: '10' },
  { id: 150, phonecode: '31', country_code: 'NL', isoCode: 'NL', name: 'Netherlands', minNumPhone: '9', maxNumPhone: '11' },
  { id: 151, phonecode: '687', country_code: 'NC', isoCode: 'NC', name: 'New Caledonia', minNumPhone: '6', maxNumPhone: '6' },
  { id: 152, phonecode: '64', country_code: 'NZ', isoCode: 'NZ', name: 'New Zealand', minNumPhone: '8', maxNumPhone: '10' },
  { id: 153, phonecode: '505', country_code: 'NI', isoCode: 'NI', name: 'Nicaragua', minNumPhone: '8', maxNumPhone: '8' },
  { id: 154, phonecode: '227', country_code: 'NE', isoCode: 'NE', name: 'Niger', minNumPhone: '8', maxNumPhone: '8' },
  { id: 155, phonecode: '234', country_code: 'NG', isoCode: 'NG', name: 'Nigeria', minNumPhone: '10', maxNumPhone: '10' },
  { id: 156, phonecode: '683', country_code: 'NU', isoCode: 'NU', name: 'Niue', minNumPhone: '4', maxNumPhone: '7' },
  { id: 157, phonecode: '850', country_code: 'KP', isoCode: 'KP', name: 'North Korea', minNumPhone: '10', maxNumPhone: '10' },
  { id: 158, phonecode: '389', country_code: 'MK', isoCode: 'MK', name: 'North Macedonia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 159, phonecode: '1-670', country_code: 'MP', isoCode: 'MP', name: 'Northern Mariana Islands', minNumPhone: '10', maxNumPhone: '10' },
  { id: 160, phonecode: '47', country_code: 'NO', isoCode: 'NO', name: 'Norway', minNumPhone: '8', maxNumPhone: '8' },
  { id: 161, phonecode: '968', country_code: 'OM', isoCode: 'OM', name: 'Oman', minNumPhone: '8', maxNumPhone: '8' },
  { id: 162, phonecode: '92', country_code: 'PK', isoCode: 'PK', name: 'Pakistan', minNumPhone: '10', maxNumPhone: '10' },
  { id: 163, phonecode: '680', country_code: 'PW', isoCode: 'PW', name: 'Palau', minNumPhone: '7', maxNumPhone: '7' },
  { id: 164, phonecode: '970', country_code: 'PS', isoCode: 'PS', name: 'Palestine', minNumPhone: '9', maxNumPhone: '9' },
  { id: 165, phonecode: '507', country_code: 'PA', isoCode: 'PA', name: 'Panama', minNumPhone: '7', maxNumPhone: '8' },
  { id: 166, phonecode: '675', country_code: 'PG', isoCode: 'PG', name: 'Papua New Guinea', minNumPhone: '8', maxNumPhone: '8' },
  { id: 167, phonecode: '595', country_code: 'PY', isoCode: 'PY', name: 'Paraguay', minNumPhone: '9', maxNumPhone: '9' },
  { id: 168, phonecode: '51', country_code: 'PE', isoCode: 'PE', name: 'Peru', minNumPhone: '9', maxNumPhone: '9' },
  { id: 169, phonecode: '63', country_code: 'PH', isoCode: 'PH', name: 'Philippines', minNumPhone: '10', maxNumPhone: '10' },
  { id: 170, phonecode: '872', country_code: 'PN', isoCode: 'PN', name: 'Pitcairn Islands', minNumPhone: '6', maxNumPhone: '12' },
  { id: 171, phonecode: '48', country_code: 'PL', isoCode: 'PL', name: 'Poland', minNumPhone: '9', maxNumPhone: '9' },
  { id: 172, phonecode: '351', country_code: 'PT', isoCode: 'PT', name: 'Portugal', minNumPhone: '9', maxNumPhone: '9' },
  { id: 173, phonecode: '1-787', country_code: 'PR', isoCode: 'PR', name: 'Puerto Rico', minNumPhone: '10', maxNumPhone: '10' },
  { id: 174, phonecode: '974', country_code: 'QA', isoCode: 'QA', name: 'Qatar', minNumPhone: '8', maxNumPhone: '8' },
  { id: 175, phonecode: '262', country_code: 'RE', isoCode: 'RE', name: 'Reunion', minNumPhone: '9', maxNumPhone: '9' },
  { id: 176, phonecode: '40', country_code: 'RO', isoCode: 'RO', name: 'Romania', minNumPhone: '9', maxNumPhone: '9' },
  { id: 177, phonecode: '7', country_code: 'RU', isoCode: 'RU', name: 'Russia', minNumPhone: '10', maxNumPhone: '10' },
  { id: 178, phonecode: '250', country_code: 'RW', isoCode: 'RW', name: 'Rwanda', minNumPhone: '9', maxNumPhone: '9' },
  { id: 179, phonecode: '590', country_code: 'BL', isoCode: 'BL', name: 'Saint Barthelemy', minNumPhone: '9', maxNumPhone: '9' },
  { id: 180, phonecode: '290', country_code: 'SH', isoCode: 'SH', name: 'Saint Helena', minNumPhone: '5', maxNumPhone: '5' },
  { id: 181, phonecode: '1-869', country_code: 'KN', isoCode: 'KN', name: 'Saint Kitts and Nevis', minNumPhone: '10', maxNumPhone: '10' },
  { id: 182, phonecode: '1-758', country_code: 'LC', isoCode: 'LC', name: 'Saint Lucia', minNumPhone: '10', maxNumPhone: '10' },
  { id: 183, phonecode: '590', country_code: 'MF', isoCode: 'MF', name: 'Saint Martin', minNumPhone: '9', maxNumPhone: '9' },
  { id: 184, phonecode: '508', country_code: 'PM', isoCode: 'PM', name: 'Saint Pierre and Miquelon', minNumPhone: '6', maxNumPhone: '9' },
  { id: 185, phonecode: '1-784', country_code: 'VC', isoCode: 'VC', name: 'Saint Vincent and the Grenadines', minNumPhone: '10', maxNumPhone: '10' },
  { id: 186, phonecode: '685', country_code: 'WS', isoCode: 'WS', name: 'Samoa', minNumPhone: '7', maxNumPhone: '10' },
  { id: 187, phonecode: '378', country_code: 'SM', isoCode: 'SM', name: 'San Marino', minNumPhone: '8', maxNumPhone: '8' },
  { id: 188, phonecode: '239', country_code: 'ST', isoCode: 'ST', name: 'Sao Tome and Principe', minNumPhone: '7', maxNumPhone: '7' },
  { id: 189, phonecode: '966', country_code: 'SA', isoCode: 'SA', name: 'Saudi Arabia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 190, phonecode: '221', country_code: 'SN', isoCode: 'SN', name: 'Senegal', minNumPhone: '9', maxNumPhone: '9' },
  { id: 191, phonecode: '381', country_code: 'RS', isoCode: 'RS', name: 'Serbia', minNumPhone: '8', maxNumPhone: '10' },
  { id: 192, phonecode: '248', country_code: 'SC', isoCode: 'SC', name: 'Seychelles', minNumPhone: '7', maxNumPhone: '7' },
  { id: 193, phonecode: '232', country_code: 'SL', isoCode: 'SL', name: 'Sierra Leone', minNumPhone: '8', maxNumPhone: '8' },
  { id: 194, phonecode: '65', country_code: 'SG', isoCode: 'SG', name: 'Singapore', minNumPhone: '8', maxNumPhone: '8' },
  { id: 195, phonecode: '1-721', country_code: 'SX', isoCode: 'SX', name: 'Sint Maarten', minNumPhone: '10', maxNumPhone: '10' },
  { id: 196, phonecode: '421', country_code: 'SK', isoCode: 'SK', name: 'Slovakia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 197, phonecode: '386', country_code: 'SI', isoCode: 'SI', name: 'Slovenia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 198, phonecode: '677', country_code: 'SB', isoCode: 'SB', name: 'Solomon Islands', minNumPhone: '5', maxNumPhone: '7' },
  { id: 199, phonecode: '252', country_code: 'SO', isoCode: 'SO', name: 'Somalia', minNumPhone: '7', maxNumPhone: '9' },
  { id: 200, phonecode: '27', country_code: 'ZA', isoCode: 'ZA', name: 'South Africa', minNumPhone: '5', maxNumPhone: '9' },
  { id: 201, phonecode: '82', country_code: 'KR', isoCode: 'KR', name: 'South Korea', minNumPhone: '9', maxNumPhone: '10' },
  { id: 202, phonecode: '211', country_code: 'SS', isoCode: 'SS', name: 'South Sudan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 203, phonecode: '34', country_code: 'ES', isoCode: 'ES', name: 'Spain', minNumPhone: '9', maxNumPhone: '9' },
  { id: 204, phonecode: '94', country_code: 'LK', isoCode: 'LK', name: 'Sri Lanka', minNumPhone: '9', maxNumPhone: '9' },
  { id: 205, phonecode: '249', country_code: 'SD', isoCode: 'SD', name: 'Sudan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 206, phonecode: '597', country_code: 'SR', isoCode: 'SR', name: 'Suriname', minNumPhone: '7', maxNumPhone: '7' },
  { id: 207, phonecode: '47', country_code: 'SJ', isoCode: 'SJ', name: 'Svalbard and Jan Mayen', minNumPhone: '8', maxNumPhone: '8' },
  { id: 208, phonecode: '46', country_code: 'SE', isoCode: 'SE', name: 'Sweden', minNumPhone: '9', maxNumPhone: '9' },
  { id: 209, phonecode: '41', country_code: 'CH', isoCode: 'CH', name: 'Switzerland', minNumPhone: '9', maxNumPhone: '9' },
  { id: 210, phonecode: '963', country_code: 'SY', isoCode: 'SY', name: 'Syria', minNumPhone: '9', maxNumPhone: '9' },
  { id: 211, phonecode: '886', country_code: 'TW', isoCode: 'TW', name: 'Taiwan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 212, phonecode: '992', country_code: 'TJ', isoCode: 'TJ', name: 'Tajikistan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 213, phonecode: '255', country_code: 'TZ', isoCode: 'TZ', name: 'Tanzania', minNumPhone: '9', maxNumPhone: '9' },
  { id: 214, phonecode: '66', country_code: 'TH', isoCode: 'TH', name: 'Thailand', minNumPhone: '9', maxNumPhone: '9' },
  { id: 215, phonecode: '670', country_code: 'TL', isoCode: 'TL', name: 'Timor-Leste', minNumPhone: '8', maxNumPhone: '8' },
  { id: 216, phonecode: '228', country_code: 'TG', isoCode: 'TG', name: 'Togo', minNumPhone: '8', maxNumPhone: '8' },
  { id: 217, phonecode: '690', country_code: 'TK', isoCode: 'TK', name: 'Tokelau', minNumPhone: '4', maxNumPhone: '7' },
  { id: 218, phonecode: '676', country_code: 'TO', isoCode: 'TO', name: 'Tonga', minNumPhone: '7', maxNumPhone: '7' },
  { id: 219, phonecode: '1-868', country_code: 'TT', isoCode: 'TT', name: 'Trinidad and Tobago', minNumPhone: '10', maxNumPhone: '10' },
  { id: 220, phonecode: '216', country_code: 'TN', isoCode: 'TN', name: 'Tunisia', minNumPhone: '8', maxNumPhone: '8' },
  { id: 221, phonecode: '90', country_code: 'TR', isoCode: 'TR', name: 'Turkey', minNumPhone: '10', maxNumPhone: '10' },
  { id: 222, phonecode: '993', country_code: 'TM', isoCode: 'TM', name: 'Turkmenistan', minNumPhone: '8', maxNumPhone: '8' },
  { id: 223, phonecode: '1-649', country_code: 'TC', isoCode: 'TC', name: 'Turks and Caicos', minNumPhone: '10', maxNumPhone: '10' },
  { id: 224, phonecode: '688', country_code: 'TV', isoCode: 'TV', name: 'Tuvalu', minNumPhone: '6', maxNumPhone: '7' },
  { id: 225, phonecode: '256', country_code: 'UG', isoCode: 'UG', name: 'Uganda', minNumPhone: '9', maxNumPhone: '9' },
  { id: 226, phonecode: '380', country_code: 'UA', isoCode: 'UA', name: 'Ukraine', minNumPhone: '9', maxNumPhone: '9' },
  { id: 227, phonecode: '971', country_code: 'AE', isoCode: 'AE', name: 'United Arab Emirates', minNumPhone: '9', maxNumPhone: '9' },
  { id: 228, phonecode: '44', country_code: 'GB', isoCode: 'GB', name: 'United Kingdom', minNumPhone: '10', maxNumPhone: '10' },
  { id: 229, phonecode: '1', country_code: 'US', isoCode: 'US', name: 'United States', minNumPhone: '10', maxNumPhone: '10' },
  { id: 230, phonecode: '598', country_code: 'UY', isoCode: 'UY', name: 'Uruguay', minNumPhone: '8', maxNumPhone: '8' },
  { id: 231, phonecode: '998', country_code: 'UZ', isoCode: 'UZ', name: 'Uzbekistan', minNumPhone: '9', maxNumPhone: '9' },
  { id: 232, phonecode: '678', country_code: 'VU', isoCode: 'VU', name: 'Vanuatu', minNumPhone: '7', maxNumPhone: '7' },
  { id: 233, phonecode: '379', country_code: 'VA', isoCode: 'VA', name: 'Vatican City', minNumPhone: '9', maxNumPhone: '10' },
  { id: 234, phonecode: '58', country_code: 'VE', isoCode: 'VE', name: 'Venezuela', minNumPhone: '10', maxNumPhone: '10' },
  { id: 235, phonecode: '84', country_code: 'VN', isoCode: 'VN', name: 'Vietnam', minNumPhone: '9', maxNumPhone: '9' },
  { id: 236, phonecode: '681', country_code: 'WF', isoCode: 'WF', name: 'Wallis and Futuna', minNumPhone: '6', maxNumPhone: '6' },
  { id: 237, phonecode: '212', country_code: 'EH', isoCode: 'EH', name: 'Western Sahara', minNumPhone: '9', maxNumPhone: '9' },
  { id: 238, phonecode: '967', country_code: 'YE', isoCode: 'YE', name: 'Yemen', minNumPhone: '9', maxNumPhone: '9' },
  { id: 239, phonecode: '260', country_code: 'ZM', isoCode: 'ZM', name: 'Zambia', minNumPhone: '9', maxNumPhone: '9' },
  { id: 240, phonecode: '263', country_code: 'ZW', isoCode: 'ZW', name: 'Zimbabwe', minNumPhone: '9', maxNumPhone: '9' },

];
